//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Rounds
{
    public int ID { get; set; }
    public Nullable<int> rounds1 { get; set; }
    public string challenger1 { get; set; }
    public string challenger2 { get; set; }
    public string result { get; set; }
    public string winner { get; set; }
}
